### ISSUE TITLE
Pip installation in Python 3.5 fails with "AttributeError: '_NamespacePath' object has no attribute 'sort' "

### ISSUE THREAD

**Issue by MJRinne** [google/gtfs-realtime-bindings#33]
I'm in the process of upgrading our environment to python 3, but gtfs-realtime-bindings refuses to install. This is what I get:

```
$ pip install --upgrade gtfs-realtime-bindings
Collecting gtfs-realtime-bindings
  Downloading https://files.pythonhosted.org/packages/c8/ae/a62dba2b0eef515ce803ceb9329c4d196127e10d6e218ca9a46b3b0610fe/gtfs-realtime-bindings-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cbbnx7ju/gtfs-realtime-bindings/
```

Python 3.5.2 (default, Nov 23 2017), pip 10.0.1, Setuptools 20.7.0. Freshly generated ubuntu/xenial64 box in Vagrant.

Wouldn't be surprised to find something wrong with my environment, but 46 other python libraries installed ok, so something looks special about this one.

**Comment by MJRinne** [comment]
It was my environment indeed. Setuptools had not upgraded, the latest one is 39.0.1. Installation passed after the upgrade.

I still don't know why the problem manifested only with gtfs-realtime-bindings. Also, exactly the same error was observed earlier in #21. Closing.
